### ISSUE TITLE
How to set playback speed?

### ISSUE THREAD

**Issue by sirhvd** [dailymotion/dailymotion-sdk-js#77]
I'm trying set default playback speed for the player. 
But I can't find an option for playback speed. 
As the video player, it really needs playback speed options.

Thank you. Help you will support playback speed option soon.

**Comment by mccarthypaulmichael** [comment]
Hi Sirhvd, thanks for the comment about using our player, unfortunately, this feature isn't available yet via our Player API in order to change the player back rate of the video. However, it is in the pipeline for our product and will be considered for development in the near future. 

Thanks for showing interesting for this feature, if you could tell us more about why you'd like it and how you plan on using it, that would be great.

**Comment by lawchihon** [comment]
> Thanks for showing interesting for this feature, if you could tell us more about why you'd like it and how you plan on using it, that would be great.

Any update for it?

**Comment by eggermann** [comment]
Any update for it? it s a very important feature for that player!

**Comment by Cycymomo** [comment]
hey 👋 closing this issue as we deprecate this integration method.
We no longer support this SDK for Player integration. It can be used for interaction with the Data API only.
The Player should be embedded using the new default Player integration method, info can be found [here](https://developer.dailymotion.com/player/#embed-website).

------

Concerning the Playback Speed it's now possible with our new Product

[Documentation](https://developers.dailymotion.com/player/#methods) > Player methods > setPlaybackSpeed()
