### ISSUE TITLE
Dailymotion site with old browsers

### ISSUE THREAD

**Issue by joaopa00** [dailymotion/dailymotion-sdk-js#88]
Since a few months, my embeded video on my website do not play in my TCL smart tv (looks like OS is TCL OS, not android, Roku...)
navigator.useragent is chrome42

TCL did not publish any firmware update for my tv.
How to bypass this problem?

**Comment by mccarthypaulmichael** [comment]
Hi @joaopa00,

Sorry that you're having the issue with your TV. The minimum version of Chrome that we support since mid-2020 is v47. Please check the below link which highlights what devices and features are supported by Dailymotion. (https://faq.dailymotion.com/hc/en-us/articles/360026614654-What-are-the-devices-and-features-supported-by-Dailymotion-).
